
development:
  adapter: mysql2
  host: <%= ENV['DEV_DATABASE_HOST'] %>
  database: <%= ENV['DEV_DATABASE'] %>
  username: <%= ENV['DEV_DATABASE_USER'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>

test:
  adapter: mysql2
  host: <%= ENV['TEST_DATABASE_HOST'] %>
  database: <%= ENV['TEST_DATABASE'] %>
  username: <%= ENV['TEST_DATABASE_USER'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>

production:
  adapter: mysql2
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
